import type { Metadata } from "next";
import "./globals.css";
import { ReactLenis } from "@/lib/smooth-scroll";
import NavBarProvider from "@/components/providers/navbar-provider";
import ppNeueMonteralBook from "@/lib/font";

export const metadata: Metadata = {
  title: "Cell Capital - success oriented grant writing agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${ppNeueMonteralBook.variable} font-sans heantialiased`}
        >
          <NavBarProvider>{children}</NavBarProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
