import type { Metadata } from "next";
import helveticaNeue from "@/lib/font";
import "./globals.css";
import { ReactLenis } from "@/lib/smooth-scroll";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ReactLenis root>
				<body className={`${helveticaNeue.variable} font-sans heantialiased`}>
					{children}
				</body>
			</ReactLenis>
		</html>
	);
}
